name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        uses: adityaa30/check-commit@v0.1

